apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cadvisor
    app.kubernetes.io/part-of: kubiquest
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cadvisor
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      honorLabels: true
      relabelings:
        # Ajouter le nom du noeud comme label
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
