apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting
  labels:
    app.kubernetes.io/name: reporting
    app.kubernetes.io/part-of: kubiquest
    environment: production
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: reporting
            app.kubernetes.io/part-of: kubiquest
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: registry-secret
          containers:
            - name: reporting
              image: ghcr.io/kubiquest/reporting:latest
              envFrom:
                - secretRef:
                    name: mysql-secret
                - secretRef:
                    name: msteams-secret
              env:
                - name: DB_HOST
                  value: mysql.databases.svc.cluster.local
                - name: DB_PORT
                  value: "3306"
              resources:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
                  cpu: 100m
